base:
  # Number of processes to start
  process_count: 2
  # Number of images generated per process
  count_per_process: 2
  # Whether to generate VOC data
  gen_voc: True
  gen_lsvt: False

provider:
  # Configuration for selecting corpus
  text:
    - name: english
      # Path to the corpus text
      path: assets/corpus/number.txt
      # Probability of selecting this corpus when generating text
      probability: 0.8
      # Method of reading the corpus (line by line: line, word by word: word)
      type: line
      # Range of generated text length
      len_range: (20, 40)
    # - name: chinese
    #   path: assets/corpus/sentence.txt
    #   probability: 0.3
    #   type: line
    #   len_range: (2, 20)
    # - name: random_character
    #   path: assets/corpus/chinese_synthetic.txt
    #   probability: 0.1
    #   type: word
    #   len_range: (2, 20)

  # Candidate area generation configuration
  smooth_area:
    down_scale: 32
    anchor_ratio: (0.17, 0.25, 0.5, 1.0, 2.0, 4.0, 6)
    anchor_scale: (8, 16, 24, 32, 48, 64, 72, 90)

  # Background image selection configuration
  bg_img:
    # Select from disk
    - type: from_dir
      # Path to the background images for generating images
      dir: assets/img
      # Probability of selecting a background image from disk
      probability: 0.8
    # Automatically generate
    - type: from_generate
      # Probability of selecting an automatically generated background image
      probability: 0.2
      width_range: (1000, 1500)
      height_range: (1000, 1500)

  # Text image configuration
  text_img:
    # Path to font files
    font_file_dir: assets/font
    # Output directory for text images
    text_img_output_dir: output/text_img
    # Output directory for text image JSON information
    text_img_info_output_dir: output/text_img_info
    # Minimum font size
    font_min_size: 15
    # Maximum font size
    font_max_size: 50
    # Probability of using specified colors for text (as opposed to automatically selected colors)
    use_char_common_color_probability: 0.5
    # List of optional colors for specified fonts (when generating text images, colors will be selected from the following list for text color)
    char_common_color_list:
      - (0,0,0,255)
      - (255,0,0,255)
    # Width of the text border
    char_border_width: 0
    # Color of the text border
    char_border_color: (255,255,0,255)
    # Automatically pad to the specified long/short edge ratio
    auto_padding_to_ratio: 10

  # Layout configuration
  layout:
    # Output directory for layout files
    out_put_dir: output
    # Range of rotation angles for pasted images
    rotate_angle_range: (-8, 8)
    # Various layout modes and their selection probabilities
    strategy_list:
      # - name: HorizontalStrategy
      #   probability: 0.4
      - name: VerticalStrategy
        probability: 0.8
      # - name: HorizontalFlowStrategy
      #   probability: 0.4
      # - name: VerticalFlowStrategy
      #   probability: 0.4
      - name: RandomPasteStrategy
        probability: 0.2
      # - name: CustomizationStrategy1
      #   probability: 0.1
